### PR TITLE
Add possibility to use public IP

### PR DESCRIPTION
**Pull request by feraudet**
Hello,

This PR add possibility to use public IP instead private one

### CODE REVIEW

**Comment by mateuszkwiatkowski** [comment]
Hi, we're also interested in using this feature. What's preventing this PR from being merged?

**Comment by jimsheldon** [comment]
@feraudet thanks for the contribution, sorry for the delay.  We will review this in the next few days.

**Comment by jimsheldon** [comment]
Sorry this took so long!  We made changes to our process around pull requests, hopefully we'll be faster in the future.

**Comment by jimsheldon** [comment]
Published new release with this feature https://github.com/meltwater/terraform-aws-asg-dns-handler/releases/tag/v2.1.0

**Pull request merged**
