### PR TITLE
Upgrade Lambda runtime to Python3.8

### PR DESCRIPTION
**Pull request by jcaffet**
Upgrade Lambda runtime to Python3.8

### CODE REVIEW

**Comment by jimsheldon** [comment]
Thanks for submitting this!  Sorry for the delay.  We will review asap.

**Comment by mlorenz2** [comment]
Hi,
are there any updates? Since AWS announced the end of python 2 in AWS lambda, this PR merge would be appreciated.
https://aws.amazon.com/de/blogs/compute/announcing-end-of-support-for-python-2-7-in-aws-lambda/

**Comment by jimsheldon** [comment]
@mlorenz2 sorry for the extreme delay on this, we will look into this asap

**Review by cmckeen — APPROVED** [review]

**Comment by cmckeen** [comment]
Thanks for your patience, v2.1.1 has been released with this update.

**Pull request merged**
